apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-iot
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: p2/
    repoURL: https://gitlab.com/Toufa7/inception-of-things.git # TODO: replace with github repo
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false