apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-iot
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: p2/confs
    repoURL: https://github.com/Toufa7/otoufah-iot.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false