apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-iot
spec:
  destination:
    namespace: ''
    server: https://kubernetes.default.svc
  source:
    path: p2/
    repoURL: git@gitlab.com:Toufa7/inception-of-things.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

# TODO: Since our repo is private i've tried to $k cp id_rsa -n argocd argocd-server-99c485944-m48sz:/home/argocd