Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.define "yjaadounS" do |master|
    master.vm.hostname = "yjaadounS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.network "forwarded_port", guest: 80, host: 8080
    master.vm.provider "virtualbox" do |vb|
      vb.name = "yjaadounS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    master.vm.provision "file", source: "./scripts/setupK3s.sh", destination: "/home/vagrant/setup.sh"
    master.vm.synced_folder "./confs", "/home/vagrant/confs"
    master.vm.provision "shell", inline: "chmod +x /home/vagrant/setup.sh && /home/vagrant/setup.sh"
  end
end
