Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
    config.vm.define "ibnadaS" do |master|
    master.vm.hostname = "ibnadaS"
    master.vm.network "private_network", ip: "192.168.56.110"
    #master.disksize.size = '10GB'
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    master.vm.provision "file", source: "./scripts/setupK3s.sh", destination: "/home/vagrant/setup.sh"
    master.vm.synced_folder "./confs", "/home/vagrant/confs"
    master.vm.provision "shell", inline: "chmod +x /home/vagrant/setup.sh && /home/vagrant/setup.sh"

  end
end