Vagrant.configure("2") do |config|
  
    config.vm.define "yjaadounS" do |ibnadaS|
      ibnadaS.vm.box = "bento/ubuntu-24.04"
      ibnadaS.vm.hostname = "yjaadounS"
      ibnadaS.vm.network "private_network", ip: "192.168.56.110", adapter: 2
      ibnadaS.vm.provider "virtualbox" do |vb|
        vb.name = "yjaadounS"
        vb.memory = "1024"
        vb.cpus = 1
      end
      
      ibnadaS.vm.provision "shell",  path: "scripts/install_server.sh"
    end    
end
    