Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.define "ibnadaS" do |master|
    master.vm.hostname = "ibnadaS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    master.vm.provision "file", source: "./scripts/setupK3s.sh", destination: "/home/vagrant/setup.sh"
    master.vm.provision "shell", inline: "chmod +x /home/vagrant/setup.sh && /home/vagrant/setup.sh"
    
    master.vm.provision "shell", inline: <<-SHELL
      sudo cat /var/lib/rancher/k3s/server/node-token > /home/vagrant/node-token
    SHELL
  end
  
  config.vm.define "ibnadaSW" do |worker|
    worker.vm.hostname = "ibnadaSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    worker.vm.provision "shell", inline: <<-SHELL
      TOKEN=$(vagrant ssh server -c "cat /home/vagrant/node-token" 2>/dev/null)
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=${TOKEN} sh -
    SHELL
  end
end