Vagrant.configure("2") do |config|
  
  config.vm.define "ibnadaS" do |ibnadaS|
    ibnadaS.vm.box = "bento/ubuntu-24.04"
    ibnadaS.vm.hostname = "ibnadaS"
    ibnadaS.vm.network "private_network", ip: "192.168.56.110"
    ibnadaS.vm.provider "virtualbox" do |vb|
      vb.name = "ibnadaS"
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    ibnadaS.vm.provision "shell", inline: <<-SHELL
      echo "K3s server provision setup start"
      echo "Installing K3s in server mode..."
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-iface eth1" sh -

      sudo systemctl enable k3s
      sudo systemctl start k3s
      sudo chmod 644 /etc/rancher/k3s/k3s.yaml

      #Sharing Node token in shared folder
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
      sudo cp /etc/rancher/k3s/k3s.yaml /vagrant/kubeconfig
      sudo sed -i 's/127.0.0.1/192.168.56.110/g' /vagrant/kubeconfig
      sudo chmod 644 /vagrant/kubeconfig

      #Sharing kube config in shared folder
      mkdir -p /home/vagrant/.kube
      sudo cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
      sudo chown vagrant:vagrant /home/vagrant/.kube/config
    
      echo "source <(kubectl completion bash)" >> ~/.bashrc
      echo "K3s server provision setup complete"
    SHELL
  end
  
  config.vm.define "ibnadaSW" do |ibnadaSW|
    ibnadaSW.vm.box = "bento/ubuntu-24.04"
    ibnadaSW.vm.hostname = "ibnadaSW"
    ibnadaSW.vm.network "private_network", ip: "192.168.56.111"
    ibnadaSW.vm.provider "virtualbox" do |vb|
      vb.name = "ibnadaSW"
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    ibnadaSW.vm.provision "shell", inline: <<-SHELL
      echo "K3s agent provision setup start"
      echo "Installing K3s in agent mode..."
      curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/node-token) INSTALL_K3S_EXEC="--node-ip=192.168.56.111" sh -

      mkdir -p /home/vagrant/.kube
      cp /vagrant/kubeconfig /home/vagrant/.kube/config
      chown vagrant:vagrant /home/vagrant/.kube/config
      echo "source <(kubectl completion bash)" >> ~/.bashrc
      echo "K3s agent setup complete"
    SHELL
  end

end
